/**
 * This class is generated by jOOQ
 */
package com.justweighit.database.jooq.tables.records;


import com.justweighit.database.jooq.tables.RecipeFood;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecipeFoodRecord extends TableRecordImpl<RecipeFoodRecord> implements Record4<Integer, String, BigDecimal, Integer> {

    private static final long serialVersionUID = 1715659411;

    /**
     * Setter for <code>public.recipe_food.recipe_id</code>.
     */
    public RecipeFoodRecord setRecipeId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.recipe_food.recipe_id</code>.
     */
    public Integer getRecipeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.recipe_food.ndbno</code>.
     */
    public RecipeFoodRecord setNdbno(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.recipe_food.ndbno</code>.
     */
    public String getNdbno() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.recipe_food.amount</code>.
     */
    public RecipeFoodRecord setAmount(BigDecimal value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.recipe_food.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.recipe_food.unit</code>.
     */
    public RecipeFoodRecord setUnit(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.recipe_food.unit</code>.
     */
    public Integer getUnit() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, BigDecimal, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, BigDecimal, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RecipeFood.RECIPE_FOOD.RECIPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return RecipeFood.RECIPE_FOOD.NDBNO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return RecipeFood.RECIPE_FOOD.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return RecipeFood.RECIPE_FOOD.UNIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRecipeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNdbno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipeFoodRecord value1(Integer value) {
        setRecipeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipeFoodRecord value2(String value) {
        setNdbno(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipeFoodRecord value3(BigDecimal value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipeFoodRecord value4(Integer value) {
        setUnit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipeFoodRecord values(Integer value1, String value2, BigDecimal value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecipeFoodRecord
     */
    public RecipeFoodRecord() {
        super(RecipeFood.RECIPE_FOOD);
    }

    /**
     * Create a detached, initialised RecipeFoodRecord
     */
    public RecipeFoodRecord(Integer recipeId, String ndbno, BigDecimal amount, Integer unit) {
        super(RecipeFood.RECIPE_FOOD);

        set(0, recipeId);
        set(1, ndbno);
        set(2, amount);
        set(3, unit);
    }
}
