/**
 * This class is generated by jOOQ
 */
package com.justweighit.database.jooq.tables.records;


import com.justweighit.database.jooq.tables.Weight;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WeightRecord extends TableRecordImpl<WeightRecord> implements Record5<String, BigDecimal, Integer, String, BigDecimal> {

    private static final long serialVersionUID = 1381062157;

    /**
     * Setter for <code>public.weight.ndbno</code>.
     */
    public WeightRecord setNdbno(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.weight.ndbno</code>.
     */
    public String getNdbno() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.weight.amount</code>.
     */
    public WeightRecord setAmount(BigDecimal value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.weight.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.weight.unit</code>.
     */
    public WeightRecord setUnit(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.weight.unit</code>.
     */
    public Integer getUnit() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.weight.description</code>.
     */
    public WeightRecord setDescription(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.weight.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.weight.grams</code>.
     */
    public WeightRecord setGrams(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.weight.grams</code>.
     */
    public BigDecimal getGrams() {
        return (BigDecimal) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, BigDecimal, Integer, String, BigDecimal> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, BigDecimal, Integer, String, BigDecimal> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Weight.WEIGHT.NDBNO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return Weight.WEIGHT.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Weight.WEIGHT.UNIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Weight.WEIGHT.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return Weight.WEIGHT.GRAMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getNdbno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getGrams();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WeightRecord value1(String value) {
        setNdbno(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WeightRecord value2(BigDecimal value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WeightRecord value3(Integer value) {
        setUnit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WeightRecord value4(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WeightRecord value5(BigDecimal value) {
        setGrams(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WeightRecord values(String value1, BigDecimal value2, Integer value3, String value4, BigDecimal value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WeightRecord
     */
    public WeightRecord() {
        super(Weight.WEIGHT);
    }

    /**
     * Create a detached, initialised WeightRecord
     */
    public WeightRecord(String ndbno, BigDecimal amount, Integer unit, String description, BigDecimal grams) {
        super(Weight.WEIGHT);

        set(0, ndbno);
        set(1, amount);
        set(2, unit);
        set(3, description);
        set(4, grams);
    }
}
