/*
 * This file is generated by jOOQ.
 */
package com.justweighit.database.jooq;


import com.justweighit.database.jooq.tables.Food;
import com.justweighit.database.jooq.tables.Nutrient;
import com.justweighit.database.jooq.tables.NutrientContent;
import com.justweighit.database.jooq.tables.Weight;
import com.justweighit.database.jooq.tables.records.FoodRecord;
import com.justweighit.database.jooq.tables.records.NutrientContentRecord;
import com.justweighit.database.jooq.tables.records.NutrientRecord;
import com.justweighit.database.jooq.tables.records.WeightRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FoodRecord> FOOD_PKEY = UniqueKeys0.FOOD_PKEY;
    public static final UniqueKey<NutrientRecord> NUTRIENT_PKEY = UniqueKeys0.NUTRIENT_PKEY;
    public static final UniqueKey<NutrientContentRecord> NUTRIENT_CONTENT_PK = UniqueKeys0.NUTRIENT_CONTENT_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<NutrientContentRecord, FoodRecord> NUTRIENT_CONTENT__NUTRIENT_CONTENT_FOOD_NDBNO_FK = ForeignKeys0.NUTRIENT_CONTENT__NUTRIENT_CONTENT_FOOD_NDBNO_FK;
    public static final ForeignKey<NutrientContentRecord, NutrientRecord> NUTRIENT_CONTENT__NUTRIENT_CONTENT_NUTRIENT_ID_FK = ForeignKeys0.NUTRIENT_CONTENT__NUTRIENT_CONTENT_NUTRIENT_ID_FK;
    public static final ForeignKey<WeightRecord, FoodRecord> WEIGHT__FOOD_WEIGHT_KEY = ForeignKeys0.WEIGHT__FOOD_WEIGHT_KEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<FoodRecord> FOOD_PKEY = Internal.createUniqueKey(Food.FOOD, "food_pkey", new TableField[] { Food.FOOD.NDBNO }, true);
        public static final UniqueKey<NutrientRecord> NUTRIENT_PKEY = Internal.createUniqueKey(Nutrient.NUTRIENT, "nutrient_pkey", new TableField[] { Nutrient.NUTRIENT.ID }, true);
        public static final UniqueKey<NutrientContentRecord> NUTRIENT_CONTENT_PK = Internal.createUniqueKey(NutrientContent.NUTRIENT_CONTENT, "nutrient_content_pk", new TableField[] { NutrientContent.NUTRIENT_CONTENT.NDBNO, NutrientContent.NUTRIENT_CONTENT.NUTRIENT_ID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<NutrientContentRecord, FoodRecord> NUTRIENT_CONTENT__NUTRIENT_CONTENT_FOOD_NDBNO_FK = Internal.createForeignKey(Keys.FOOD_PKEY, NutrientContent.NUTRIENT_CONTENT, "nutrient_content_food_ndbno_fk", new TableField[] { NutrientContent.NUTRIENT_CONTENT.NDBNO }, true);
        public static final ForeignKey<NutrientContentRecord, NutrientRecord> NUTRIENT_CONTENT__NUTRIENT_CONTENT_NUTRIENT_ID_FK = Internal.createForeignKey(Keys.NUTRIENT_PKEY, NutrientContent.NUTRIENT_CONTENT, "nutrient_content_nutrient_id_fk", new TableField[] { NutrientContent.NUTRIENT_CONTENT.NUTRIENT_ID }, true);
        public static final ForeignKey<WeightRecord, FoodRecord> WEIGHT__FOOD_WEIGHT_KEY = Internal.createForeignKey(Keys.FOOD_PKEY, Weight.WEIGHT, "food_weight_key", new TableField[] { Weight.WEIGHT.NDBNO }, true);
    }
}
