/**
 * This class is generated by jOOQ
 */
package com.justweighit.database.jooq;


import com.justweighit.database.jooq.tables.Food;
import com.justweighit.database.jooq.tables.Weight;
import com.justweighit.database.jooq.tables.records.FoodRecord;
import com.justweighit.database.jooq.tables.records.WeightRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FoodRecord> FOOD_PKEY = UniqueKeys0.FOOD_PKEY;
    public static final UniqueKey<WeightRecord> WEIGHT_PKEY = UniqueKeys0.WEIGHT_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<WeightRecord, FoodRecord> WEIGHT__FOOD_WEIGHT_KEY = ForeignKeys0.WEIGHT__FOOD_WEIGHT_KEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<FoodRecord> FOOD_PKEY = createUniqueKey(Food.FOOD, "food_pkey", Food.FOOD.NDBNO);
        public static final UniqueKey<WeightRecord> WEIGHT_PKEY = createUniqueKey(Weight.WEIGHT, "weight_pkey", Weight.WEIGHT.NDBNO);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<WeightRecord, FoodRecord> WEIGHT__FOOD_WEIGHT_KEY = createForeignKey(com.justweighit.database.jooq.Keys.FOOD_PKEY, Weight.WEIGHT, "weight__food_weight_key", Weight.WEIGHT.NDBNO);
    }
}
