/*
 * This file is generated by jOOQ.
 */
package com.justweighit.database.jooq;


import com.justweighit.database.jooq.tables.Food;
import com.justweighit.database.jooq.tables.Nutrient;
import com.justweighit.database.jooq.tables.NutrientContent;
import com.justweighit.database.jooq.tables.Weight;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 964043727;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.food</code>.
     */
    public final Food FOOD = Food.FOOD;

    /**
     * The table <code>public.nutrient</code>.
     */
    public final Nutrient NUTRIENT = Nutrient.NUTRIENT;

    /**
     * The table <code>public.nutrient_content</code>.
     */
    public final NutrientContent NUTRIENT_CONTENT = NutrientContent.NUTRIENT_CONTENT;

    /**
     * The table <code>public.weight</code>.
     */
    public final Weight WEIGHT = Weight.WEIGHT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Food.FOOD,
            Nutrient.NUTRIENT,
            NutrientContent.NUTRIENT_CONTENT,
            Weight.WEIGHT);
    }
}
