/**
 * This class is generated by jOOQ
 */
package com.justweighit.database.jooq;


import com.justweighit.database.jooq.tables.Food;
import com.justweighit.database.jooq.tables.Weight;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.food</code>.
     */
    public static final Food FOOD = com.justweighit.database.jooq.tables.Food.FOOD;

    /**
     * The table <code>public.weight</code>.
     */
    public static final Weight WEIGHT = com.justweighit.database.jooq.tables.Weight.WEIGHT;
}
