/*
 * This file is generated by jOOQ.
 */
package com.justweighit.database.jooq;


import com.justweighit.database.jooq.tables.Food;
import com.justweighit.database.jooq.tables.Nutrient;
import com.justweighit.database.jooq.tables.NutrientContent;
import com.justweighit.database.jooq.tables.Weight;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.food</code>.
     */
    public static final Food FOOD = Food.FOOD;

    /**
     * The table <code>public.nutrient</code>.
     */
    public static final Nutrient NUTRIENT = Nutrient.NUTRIENT;

    /**
     * The table <code>public.nutrient_content</code>.
     */
    public static final NutrientContent NUTRIENT_CONTENT = NutrientContent.NUTRIENT_CONTENT;

    /**
     * The table <code>public.weight</code>.
     */
    public static final Weight WEIGHT = Weight.WEIGHT;
}
