/**
 * This class is generated by jOOQ
 */
package com.justweighit.database.jooq;


import com.justweighit.database.jooq.tables.Food;
import com.justweighit.database.jooq.tables.Nutrient;
import com.justweighit.database.jooq.tables.NutrientContent;
import com.justweighit.database.jooq.tables.Recipe;
import com.justweighit.database.jooq.tables.RecipeFood;
import com.justweighit.database.jooq.tables.RelatedFood;
import com.justweighit.database.jooq.tables.Weight;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.food</code>.
     */
    public static final Food FOOD = com.justweighit.database.jooq.tables.Food.FOOD;

    /**
     * The table <code>public.nutrient</code>.
     */
    public static final Nutrient NUTRIENT = com.justweighit.database.jooq.tables.Nutrient.NUTRIENT;

    /**
     * The table <code>public.nutrient_content</code>.
     */
    public static final NutrientContent NUTRIENT_CONTENT = com.justweighit.database.jooq.tables.NutrientContent.NUTRIENT_CONTENT;

    /**
     * The table <code>public.recipe</code>.
     */
    public static final Recipe RECIPE = com.justweighit.database.jooq.tables.Recipe.RECIPE;

    /**
     * The table <code>public.recipe_food</code>.
     */
    public static final RecipeFood RECIPE_FOOD = com.justweighit.database.jooq.tables.RecipeFood.RECIPE_FOOD;

    /**
     * The table <code>public.related_food</code>.
     */
    public static final RelatedFood RELATED_FOOD = com.justweighit.database.jooq.tables.RelatedFood.RELATED_FOOD;

    /**
     * The table <code>public.weight</code>.
     */
    public static final Weight WEIGHT = com.justweighit.database.jooq.tables.Weight.WEIGHT;
}
